name:                log4hs
version:             0.1.0.0
github:              "jmdurr/log4hs"
license:             BSD3
author:              "Jonathan Durr"
maintainer:          "jmdurr@gmail.com"
copyright:           "2019 Jonathan Durr All Rights Reserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jmdurr/log4hs#readme>

dependencies:
- base >= 4.7 && < 5
- text
- attoparsec
- time
- transformers
- template-haskell
- split
- stm
- stm-chans
- mtl
- directory
- filepath
- zlib
- bytestring

when:
- condition: os(windows)
  then:
    dependencies:
    - Win32
  else:
    dependencies:
    - unix

library:
  source-dirs: src/
  when:
  - condition: 'os(windows)'
    then:
      source-dirs: windows/
    else:
      source-dirs: unix/
  exposed-modules:
    - Logging.Log4hs
    - Logging.Log4hs.Appender.Console
    - Logging.Log4hs.Appender.Async
    - Logging.Log4hs.Layout.Pattern
    - Logging.Log4hs.TH.Log4hs
    - System.Process

tests:
  log4h-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - log4hs
    - hspec
    - hspec-core
